[build-system]
requires = ["flit_core >=2,<3"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "httpx_oauth"
dist-name = "httpx-oauth"
author = "FranÃ§ois Voron"
author-email = "fvoron@gmail.com"
home-page = "https://github.com/frankie567/httpx-oauth"
classifiers = [
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3 :: Only",
]
description-file = "README.md"
requires-python = ">=3.7"
requires = [
    "httpx ==0.11.0",
    "typing-extensions",
]

[tool.flit.metadata.requires-extra]

[tool.flit.metadata.urls]
Documentation = "https://frankie567.github.io/httpx-oauth/"
